import type { Metadata } from "next";

// Canonical production origin for SEO (canonical URLs, sitemap, Open Graph).
// Hardcoded rather than read from SITE_URL, which falls back to localhost
// and would otherwise leak into canonical tags on preview deployments.
export const SITE_URL = "https://www.thronesideassets.com";

export const SITE_NAME = "Throneside Assets";

export const HOME_TITLE = "Throneside Assets — Vetted UK Property Deals, Weekly";
export const HOME_DESCRIPTION =
  "We source, analyse, and deliver off-market property investment opportunities across the UK. You review the numbers and decide — no searching required.";

// Public, indexable pages — drives sitemap.xml.
export const publicRoutes: {
  path: string;
  changeFrequency: "daily" | "weekly" | "monthly" | "yearly";
  priority: number;
}[] = [
  { path: "/", changeFrequency: "weekly", priority: 1 },
  { path: "/deals", changeFrequency: "weekly", priority: 0.9 },
  { path: "/pricing", changeFrequency: "monthly", priority: 0.9 },
  { path: "/about", changeFrequency: "monthly", priority: 0.8 },
  { path: "/news", changeFrequency: "daily", priority: 0.7 },
  { path: "/faq", changeFrequency: "monthly", priority: 0.7 },
  { path: "/contact", changeFrequency: "yearly", priority: 0.7 },
  { path: "/join", changeFrequency: "yearly", priority: 0.6 },
  { path: "/terms", changeFrequency: "yearly", priority: 0.3 },
];

// Generated by src/app/opengraph-image.tsx. Referenced explicitly because a
// page that sets its own openGraph loses the file-based image otherwise.
const SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Throneside Assets — Vetted UK property deals, delivered every week",
};

// Next.js replaces (not merges) a parent's openGraph/twitter objects when a
// page sets its own, so every page builds the full set here.
export function pageMetadata({
  title,
  description,
  path,
  absoluteTitle = false,
}: {
  title: string;
  description: string;
  path: string;
  /** Skip the "| Throneside Assets" suffix (e.g. the home page). */
  absoluteTitle?: boolean;
}): Metadata {
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_GB",
      url: path,
      title,
      description,
      images: [SHARE_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [SHARE_IMAGE],
    },
  };
}

export const noIndex: Metadata = {
  robots: { index: false, follow: false },
};
